main/urls.py
from django.urls import path

from main.views import (apartment_receipt, generate_excel,
                        generate_excel_apartment_total_file, generate_txt,
                        settings, update_fees)

app_name = 'main'

urlpatterns = [
    path('update_fees', update_fees, name='update_fees'),
    path('settings', settings, name='settings'),
    path('generate_excel', generate_excel, name='generate_excel'),
    path('generate_excel_apartment_total_file', generate_excel_apartment_total_file,
         name='generate_excel_apartment_total_file'),
    path('generate_txt', generate_txt, name='generate_txt'),
    path('apartment_receipt', apartment_receipt, name='apartment_receipt'),
]

rainbow/urls.py
from django.contrib import admin
from django.urls import include, path

from main import views
from main.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace='users')),
    path('', include('main.urls', namespace='main')),
    path('tariff/', include('tariff.urls', namespace='tariff')),
    path('repair/', include('repair.urls', namespace='repair')),
    path('', index, name='index'),
    path('update/<int:id>', views.update),

]

users/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from users.views import login

app_name = 'users'

urlpatterns = [
    path('login/', login, name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    image = models.ImageField(upload_to='users_images', null=True, blank=True)

users/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm

from users.models import User


class UserLoginForm(AuthenticationForm):

    attrs_user = {'class': 'card w-100',
                  'style': 'border-color: #D9D9D9;'
                           'padding-left: 10px;'
                           'padding-bottom: 2px;',
                  'placeholder': 'Please fill out this field Username',
                  }

    attrs_pass = {'class': 'card w-100',
                  'style': 'border-color: #D9D9D9;'
                           'padding-left: 10px;'
                           'padding-bottom: 2px;',
                  'placeholder': 'Please fill out this field Password',
                  }

    username = forms.CharField(
        widget=forms.TextInput(attrs=attrs_user)
    )

    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs=attrs_pass
        )
    )

    class Meta:
        model = User
        fields = ('username', 'password')

users/views.py
from django.contrib import auth
from django.shortcuts import HttpResponseRedirect, render
from django.urls import reverse

from users.forms import UserLoginForm


def login(request):
    if request.method == 'POST':
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = auth.authenticate(username=username, password=password)
            if user:
                auth.login(request, user)
                return HttpResponseRedirect(reverse('index'))
    else:
        form = UserLoginForm()
    context = {'login_form': form}
    return render(request, 'login.html', context)

users/templates/login.html
<div class="modal fade" id="LoginModal" tabindex="-1" aria-labelledby="loginModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header text-center custom-modal-header">
        <h5 class="modal-title w-100" style="font-size: 14px; color: #FFFFFF; font-family: Segoe UI,serif; font-weight: 400">SIGN IN</h5>
      </div>
      <form action="{% url 'users:login' %}" method="post">
        {% csrf_token %}
        <div class="modal-body">
          <div class="row mb-3">
            <div class="col">
              <label for="{{ login_form.username.id_for_label }}" class="form-label">Username:</label>
              {{ login_form.username }}
            </div>
          </div>
          <div class="row mb-3">
            <div class="col">
              <label for="{{ login_form.password.id_for_label }}" class="form-label">Password:</label>
              {{ login_form.password }}
            </div>
          </div>
          <br>
          <div class="row mb-3">
            <div class="col text-center">
              <div class="d-grid gap-3 d-md-flex justify-content-md-center">
                <a class="btn-segoe" data-bs-dismiss="modal">Cancel</a>
                <a class="btn-segoe-primary" id="saveButton">Log in</a>
                <input type="submit" class="d-none" id="submitButton">
              </div>
            </div>
          </div>
        </div>
      </form>
    </div>
  </div>
</div>

<script>
document.getElementById("saveButton").addEventListener("click", function() {
  document.getElementById("submitButton").click();
});
</script>