main/urls.py
from django.urls import path

from main.views import (apartment_receipt, generate_excel,
                        generate_excel_apartment_total_file, generate_txt,
                        settings, update_fees)

app_name = 'main'

urlpatterns = [
    path('update_fees', update_fees, name='update_fees'),
    path('settings', settings, name='settings'),
    path('generate_excel', generate_excel, name='generate_excel'),
    path('generate_excel_apartment_total_file', generate_excel_apartment_total_file,
         name='generate_excel_apartment_total_file'),
    path('generate_txt', generate_txt, name='generate_txt'),
    path('apartment_receipt', apartment_receipt, name='apartment_receipt'),
]

rainbow/urls.py
from django.contrib import admin
from django.urls import include, path

from main import views
from main.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace='users')),
    path('', include('main.urls', namespace='main')),
    path('tariff/', include('tariff.urls', namespace='tariff')),
    path('repair/', include('repair.urls', namespace='repair')),
    path('', index, name='index'),
    path('update/<int:id>', views.update),

]

repair/urls.py
from django.urls import path

from repair.views import (RepairListView, edit_repair,
                          generate_excel_repair_total_file,
                          repair_generate_excel, repair_generate_txt,
                          repair_list, repairs_receipt)

app_name = 'repair'

urlpatterns = [
    path('', RepairListView.as_view(), name='repair_list_main'),
    path('list/', repair_list, name='repair_list'),
    path('<int:pk>/edit', edit_repair, name='edit_repair'),
    path('repair_generate_txt', repair_generate_txt, name='repair_generate_txt'),
    path('repair_generate_excel', repair_generate_excel, name='repair_generate_excel'),
    path(
        'generate_excel_repair_total_file', generate_excel_repair_total_file,
        name='generate_excel_repair_total_file'
        ),
    path('repair_receipt', repairs_receipt, name='repair_receipt'),
]

main/models.py
from django.db import models

from tariff.models import Tariff


class Apartment(models.Model):
    owner = models.CharField(max_length=200)
    serialNumber = models.IntegerField()

    def __str__(self):
        return str(self.serialNumber)


class ApartmentDetail(models.Model):
    registredQt = models.IntegerField()
    livedQt = models.IntegerField()
    totalArea = models.FloatField()
    personalAccount = models.IntegerField()
    serialNumber = models.ForeignKey(to=Apartment, on_delete=models.CASCADE)
    tariff = models.ForeignKey(to=Tariff, on_delete=models.DO_NOTHING, null=True, blank=True)
    account_number = models.CharField(max_length=200)


class ApartmentCounter(models.Model):
    hot_water_previous = models.IntegerField(default=0)
    hot_water_current = models.IntegerField(default=0)
    hot_water_value = models.IntegerField(default=0)
    cold_water_previous = models.IntegerField(default=0)
    cold_water_current = models.IntegerField(default=0)
    cold_water_value = models.IntegerField(default=0)
    electricity_previous = models.IntegerField(default=0)
    electricity_current = models.IntegerField(default=0)
    electricity_value = models.IntegerField(default=0)
    wastewater_value = models.IntegerField(default=0)
    serialNumber = models.ForeignKey(to=Apartment, on_delete=models.CASCADE)


class ApartmentCharge(models.Model):
    money_deposited = models.FloatField()
    fine = models.FloatField()
    recalculation_electricity = models.FloatField(null=True, blank=True)
    recalculation_heating_rub = models.FloatField(null=True, blank=True)
    recalculation_hot_water = models.FloatField(null=True, blank=True)
    recalculation_cold_water = models.FloatField(null=True, blank=True)
    recalculation_sewage = models.FloatField(null=True, blank=True)
    recalculation_solid_waste = models.FloatField(null=True, blank=True)
    recalculation_maintenance = models.FloatField(null=True, blank=True)
    balance_start = models.FloatField(null=True, blank=True)
    serialNumber = models.ForeignKey(to=Apartment, on_delete=models.CASCADE)


class ApartmentFee(models.Model):
    maintenance = models.FloatField(null=True, blank=True)
    electricity_odn = models.FloatField(null=True, blank=True)
    lift = models.FloatField(null=True, blank=True)
    maintenance_full = models.FloatField(null=True, blank=True)
    solid_waste = models.FloatField(null=True, blank=True)
    electricity = models.FloatField(null=True, blank=True)
    heating = models.FloatField(null=True, blank=True)
    heating_rub = models.FloatField(null=True, blank=True)
    hot_water = models.FloatField(null=True, blank=True)
    hot_water_odn = models.FloatField(null=True, blank=True)
    cold_water = models.FloatField(null=True, blank=True)
    cold_water_odn = models.FloatField(null=True, blank=True)
    sewage = models.FloatField(null=True, blank=True)
    sewage_odn = models.FloatField(null=True, blank=True)
    maintenance_total = models.FloatField(null=True, blank=True)
    accrued_expenses = models.FloatField(null=True, blank=True)
    recalculation = models.FloatField(null=True, blank=True)
    balance_start = models.FloatField(null=True, blank=True)
    balance_end = models.FloatField(null=True, blank=True)
    paid = models.FloatField(null=True, blank=True)
    fine = models.FloatField(null=True, blank=True)
    total = models.FloatField(null=True, blank=True)
    serialNumber = models.ForeignKey(to=Apartment, on_delete=models.CASCADE)


class Settings(models.Model):
    month_name = models.CharField(max_length=200)
    month_to_pay = models.CharField(max_length=200)
    month_to_date = models.CharField(max_length=200)
    bill = models.CharField(max_length=200)
    pay_up_to = models.CharField(max_length=200)

    class Meta:
        verbose_name = 'setting'
        verbose_name_plural = 'settings'

repair/models.py
from django.db import models

from main.models import Apartment, ApartmentDetail
from tariff.models import Tariff


class CapitalRepair(models.Model):
    # Debt at the beginning of the month
    debt = models.FloatField(null=True, blank=True)
    # Fine
    fine = models.FloatField(null=True, blank=True)
    # Paid
    paid = models.FloatField(null=True, blank=True)
    # Recalculation
    recalculation = models.FloatField(null=True, blank=True)
    serialNumber = models.ForeignKey(to=Apartment, on_delete=models.CASCADE)

    def accrued(self):
        apartment_detail = ApartmentDetail.objects.get(serialNumber=self.serialNumber)
        tariff = Tariff.objects.get(id=apartment_detail.tariff_id)
        return round(apartment_detail.totalArea * tariff.capital_repair, 2)

    def total(self):
        total = self.accrued() + self.debt + self.fine - self.paid - self.recalculation
        return round(total, 2)

repair/forms.py
from django import forms

from .models import CapitalRepair


class CapitalRepairForm(forms.ModelForm):
    attrs = {'class': 'card w-100',
             'style': 'border-color: #D9D9D9; '
                      'padding-left: 10px;'
                      'padding-bottom: 2px;'
             }

    error_messages = {
        'invalid': 'For entering decimal numbers, please use a dot (.)'
    }

    debt = forms.FloatField(
        widget=forms.TextInput(attrs=attrs),
        error_messages=error_messages,
        initial=0
    )

    fine = forms.FloatField(
        widget=forms.TextInput(attrs=attrs),
        error_messages=error_messages,
        initial=0
        )

    paid = forms.FloatField(
        widget=forms.TextInput(attrs=attrs),
        error_messages=error_messages,
        initial=0
    )

    recalculation = forms.FloatField(
        widget=forms.TextInput(attrs=attrs),
        error_messages=error_messages,
        initial=0
    )

    class Meta:
        model = CapitalRepair
        fields = "__all__"

repair/views.py
import json

from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render
from django.urls import reverse_lazy
from django.views import View
from django.views.generic.list import ListView

from common.views import TitleMixin
from main.forms import Settings, SettingsForm
from main.models import Apartment, ApartmentDetail
from repair.excel import (export_excel_repair_total_file,
                          repair_export_client_bank,
                          repair_generate_excel_file)
from repair.forms import CapitalRepairForm
from repair.models import CapitalRepair
from repair.pdf_repair import repair_generate_pdf
from users.forms import UserLoginForm
from django.contrib.auth.decorators import login_required


def repair_list(request):
    return render(request, 'repair/repair_list.html', {
        'repairs': CapitalRepair.objects.all(),
        'apartments': Apartment.objects.all(),
        'details': ApartmentDetail.objects.all(),
    })


@login_required
def edit_repair(request, pk):
    repair = get_object_or_404(CapitalRepair, pk=pk)
    if request.method == "POST":
        repair_form = CapitalRepairForm(request.POST, instance=repair)
        if repair_form.is_valid():
            repair_form.save()
            return HttpResponse(
                status=204,
                headers={
                    'HX-Trigger': json.dumps({
                        "repairListChanged": None,
                        "showMessage": f"Данные по квартире №{repair.serialNumber} изменены."
                    })
                }
            )
    else:
        repair_form = CapitalRepairForm(instance=repair)
    return render(request, 'repair/edit.html', {
        'repair_form': repair_form,
        'repair': repair,
        'title': f'КАПИТАЛЬНЫЙ РЕМОНТ КВАРТИРА №{repair.serialNumber}',
    })


class RepairBaseView(View):
    model = CapitalRepair
    fields = '__all__'
    success_url = reverse_lazy('repair:repair_list')


class RepairListView(TitleMixin, ListView):
    template_name = 'repair/index.html'
    title = 'Капитальный ремонт'
    queryset = CapitalRepair.objects.all()
    ordering = 'serialNumber'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(RepairListView, self).get_context_data()
        context['details'] = ApartmentDetail.objects.all()
        context['apartments'] = Apartment.objects.all()
        context['repairs'] = CapitalRepair.objects.all()
        context['settings_form'] = SettingsForm(instance=Settings.objects.get(id=1))
        context['login_form'] = UserLoginForm()
        return context


def repair_generate_txt(request):
    response = repair_export_client_bank()
    return response


def repair_generate_excel(request):
    apartments = Apartment.objects.all()
    response = repair_generate_excel_file(apartments)
    return response


def generate_excel_repair_total_file(request):
    response = export_excel_repair_total_file()
    return response


def repairs_receipt(request):
    pdf = repair_generate_pdf()
    return pdf

repair/templates/repair/edit.html
{% load widget_tweaks %}
{% with WIDGET_ERROR_CLASS='is-invalid' %}
<form hx-post="{{ request.path }}" hx-headers='{"X-CSRFToken":"{{ csrf_token }}"}' class="modal-content">
    <div class="modal-content">
      <div class="modal-header text-center custom-modal-header">
        <h5 class="modal-title w-100" style="font-size: 14px; color: #FFFFFF; font-family: Segoe UI;">{{ title }}</h5>
      </div>
        <div class="modal-body">
          <div class="row mb-3">
            <div class="col">
              <label for="{{ repair_form.debt.id_for_label }}" class="form-label">Debt at the beginning of the month:</label>
                {% render_field repair_form.debt class="form-control" %}
                <div class="invalid-feedback">{{ repair_form.debt.errors|first }}</div>
            </div>
          </div>
          <div class="row mb-3">
            <div class="col">
              <label class="form-label" style="font-weight: bold">CURRENT CHARGES:</label>
               <b>{{ repair.accrued }}</b>
            </div>
          </div>
          <div class="row mb-3">
            <div class="col">
              <label for="{{ repair_form.fine.id_for_label }}" class="form-label">Fine:</label>
              {% render_field repair_form.fine class="form-control" %}
              <div class="invalid-feedback">{{ repair_form.fine.errors|first }}</div>
            </div>
          </div>
          <div class="row mb-3">
            <div class="col">
              <label for="{{ repair_form.recalculation.id_for_label }}" class="form-label">Recalculating:</label>
              {% render_field repair_form.recalculation class="form-control" %}
              <div class="invalid-feedback">{{ repair_form.recalculation.errors|first }}</div>
            </div>
          </div>
          <div class="row mb-3">
            <div class="col">
              <label for="{{ repair_form.paid.id_for_label }}" class="form-label">Paid:</label>
              {% render_field repair_form.paid class="form-control" %}
              <div class="invalid-feedback">{{ repair_form.paid.errors|first }}</div>
            </div>
          </div>
          <div class="row mb-3">
            <div class="col">
              <label class="form-label" style="font-weight: bold">TOTAL:</label>
              <b>{{ repair.total }}</b>
            </div>
          </div>
            <br>
          <div class="row mb-3">
            <div class="col text-center">
              <div class="d-grid gap-3 d-md-flex justify-content-md-center">
                <a class="btn-segoe" data-bs-dismiss="modal">Cancel</a>
                <a class="btn-segoe-primary" id="saveRepairButton">Save</a>
                <input type="submit" class="d-none" id="submitButtonSaveRepair">
              </div>
            </div>
          </div>
         <div class="form-group" style="display: none;">
              <label for="{{ repair_form.serialNumber.id_for_label }}">{{ repair_form.serialNumber.label }}</label>
              {{ repair_form.serialNumber }}
        </div>
        </div>
    </div>
</form>
{% endwith %}

<script>
  document.getElementById("saveRepairButton").addEventListener("click", function() {
    document.getElementById("submitButtonSaveRepair").click();
  });
</script>

repair/templates/repair/index.html
{% extends 'repair/repair_base.html' %}
{% load static %}


{% block css %}
    <link href="{% static 'css/apartment.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}

{% for repair in repair_list  %}
    {% for colname in repair.column_set.all  %}
        <p>{{ colname }}</p>
    {% endfor %}
{% endfor %}

    <div class="container">
    <table class="apartment-table">
        <colgroup>
            <col style="width: 3%;">
            <col style="width: 22%;">
            <col style="width: 10%;">
            <col style="width: 10%;">
            <col style="width: 10%;">
            <col style="width: 10%;">
            <col style="width: 10%;">
            <col style="width: 10%;">
            <col style="width: 10%;">
        </colgroup>
        <thead class="apartment-table">
            <tr>
                <th class="apartment-header">№</th>
                <th class="apartment-header">List of Landlords</th>
                <th class="apartment-header">Apartment size</th>
                <th class="apartment-header">Debt at the beginning of the month</th>
                <th class="apartment-header">Current charges</th>
                <th class="apartment-header">Fine</th>
                <th class="apartment-header">Recalculating</th>
                <th class="apartment-header">Paid</th>
                <th class="apartment-header">Total amount due</th>
            </tr>
        </thead>
        <tbody hx-trigger="load, repairListChanged from:body" hx-get="{% url 'repair:repair_list' %}" hx-target="this">
        <td class="dots-loader" role="status">

        </tbody>
    </table>
    </div>

<div class="back-to-top"></div>

<br>
<br>
<br>
<br>

<!-- Placeholder for the modal edit tariff -->
    <div id="modal" class="modal fade">
      <div id="dialog" class="modal-dialog modal-dialog-centered" hx-target="this"></div>
    </div>

<!-- Empty toast to show the message -->
    <div class="toast-container position-fixed top-0 end-0 p-3">
      <div id="toast" class="toast align-items-center text-white bg-success border-0" role="alert" aria-live="assertive" aria-atomic="true">
        <div class="d-flex">
          <div id="toast-body" class="toast-body"></div>
          <button type="button" class="btn-close btn-close-white me-2 m-auto" data-bs-dismiss="toast" aria-label="Close"></button>
        </div>
      </div>
    </div>

<script>
    var backToTopButton = document.querySelector('.back-to-top');

    window.addEventListener('scroll', function() {
        if (window.pageYOffset > 100) {
            backToTopButton.style.display = 'block';
        } else {
            backToTopButton.style.display = 'none';
        }
    });

    backToTopButton.addEventListener('click', function() {
        window.scrollTo({
            top: 0,
            behavior: 'smooth'
        });
    });
</script>


{% endblock %}

repair/templates/repair/repair_base.html
{% extends 'main/base.html' %}
{% load static %}

{% block css %}
{#    <link href="{% static 'css/apartment_base.css' %}" rel="stylesheet">#}
{% endblock %}

{% block repair_header %}
    <div class="container">
    <br>
    <div class="row">
        <div class="col-sm-6 text-start">
            <h1 class="special2">Complete overhaul</h1>
        </div>
    </div>
    <br>
    <div class="row">
        <div class="col-sm-6">
             <a class="btn-segoe-main" onclick="window.location.href='{% url 'repair:repair_generate_excel' %}'">Excel</a>
{#             <a class="btn-segoe-main" onclick="window.location.href='{% url 'repair:repair_receipt' %}'">Receipts</a>#}
             <a class="btn-segoe-main" onclick="window.location.href='{% url 'repair:repair_generate_txt' %}'">For bank app</a>
             <a class="btn-segoe-main" onclick="window.location.href='{% url 'repair:generate_excel_repair_total_file' %}'">Summary</a>
        </div>
    </div>
</div>

<br>

{% endblock %}

repair/templates/repair/repair_list.html
{% load humanize %}

{% for apartment in apartments %}
    {% for repair in apartment.capitalrepair_set.all %}
<tr hx-get="{% url 'repair:edit_repair' pk=repair.pk %}" hx-target="#dialog" style="cursor:pointer;">
    {% endfor %}
    <td>
        <span class="apartment-nomer">{{ apartment.serialNumber }}</span>
    </td>
    <td>
        <span class="apartment-owner">{{ apartment.owner }}</span>
    </td>
    {% for detail in apartment.apartmentdetail_set.all %}
        <td>{{ detail.totalArea }}</td>
    {% endfor %}
    {% for repair in apartment.capitalrepair_set.all %}
        <td>{{ repair.debt|intcomma }}</td>
        <td>{{ repair.accrued|intcomma }}</td>
        <td>{{ repair.fine|intcomma }}</td>
        <td>{{ repair.recalculation|intcomma }}</td>
        <td>{{ repair.paid|intcomma }}</td>
        <td>{{ repair.total|intcomma }}</td>
    {% endfor %}
</tr>
{% endfor %}