main/urls.py
from django.urls import path

from main.views import (apartment_receipt, generate_excel,
                        generate_excel_apartment_total_file, generate_txt,
                        settings, update_fees)

app_name = 'main'

urlpatterns = [
    path('update_fees', update_fees, name='update_fees'),
    path('settings', settings, name='settings'),
    path('generate_excel', generate_excel, name='generate_excel'),
    path('generate_excel_apartment_total_file', generate_excel_apartment_total_file,
         name='generate_excel_apartment_total_file'),
    path('generate_txt', generate_txt, name='generate_txt'),
    path('apartment_receipt', apartment_receipt, name='apartment_receipt'),
]

rainbow/urls.py
from django.contrib import admin
from django.urls import include, path

from main import views
from main.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace='users')),
    path('', include('main.urls', namespace='main')),
    path('tariff/', include('tariff.urls', namespace='tariff')),
    path('repair/', include('repair.urls', namespace='repair')),
    path('', index, name='index'),
    path('update/<int:id>', views.update),

]

tariff/urls.py
from django.urls import path

from tariff.views import (TariffListView, add_tariff, edit_tariff,
                          remove_tariff, tariff_list)

app_name = 'tariff'

urlpatterns = [
    path('', TariffListView.as_view(), name='tariff_list_main'),
    path('list/', tariff_list, name='tariff_list'),
    path('add/', add_tariff, name='add_tariff'),
    path('<int:pk>/edit', edit_tariff, name='edit_tariff'),
    path('<int:pk>/delete/', remove_tariff, name='tariff_delete'),
]

tariff/models.py
from django.db import models


class Tariff(models.Model):
    name = models.CharField(max_length=200)
    maintenance = models.FloatField(null=True, blank=True)
    heating = models.FloatField(null=True, blank=True)
    heating_rub = models.FloatField(null=True, blank=True)
    hot_water = models.FloatField(null=True, blank=True)
    hot_water_odn = models.FloatField(null=True, blank=True)
    cold_water = models.FloatField(null=True, blank=True)
    cold_water_odn = models.FloatField(null=True, blank=True)
    sewage = models.FloatField(null=True, blank=True)
    sewage_odn = models.FloatField(null=True, blank=True)
    solid_waste = models.FloatField(null=True, blank=True)
    electricity = models.FloatField(null=True, blank=True)
    lift = models.FloatField(null=True, blank=True)
    electricity_odn = models.FloatField(null=True, blank=True)
    capital_repair = models.FloatField(null=True, blank=True, default=0)
    multiplying_factor = models.FloatField(null=True, blank=True, default=1)

    class Meta:
        verbose_name = 'tariff'
        verbose_name_plural = 'tariffs'

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.name = self.name.capitalize()
        super(Tariff, self).save(*args, **kwargs)

tariff/forms.py
from django import forms

from .models import Tariff


class TariffForm(forms.ModelForm):
    attrs = {'class': 'card w-100',
             'style': 'border-color: #D9D9D9; '
                      'padding-left: 10px;'
                      'padding-bottom: 2px;'
             }

    error_messages = {
        'invalid': 'Для ввода дробных чисел используйте точку'
    }

    name = forms.CharField(
        widget=forms.TextInput(attrs=attrs),
        error_messages=error_messages
    )

    maintenance = forms.FloatField(
        widget=forms.TextInput(attrs=attrs),
        error_messages=error_messages,
        initial=0
    )

    heating = forms.FloatField(
        widget=forms.TextInput(attrs=attrs),
        error_messages=error_messages,
        initial=0
        )
    heating_rub = forms.FloatField(
        widget=forms.TextInput(attrs=attrs),
        error_messages=error_messages,
        initial=0
    )
    hot_water = forms.FloatField(
        widget=forms.TextInput(attrs=attrs),
        error_messages=error_messages,
        initial=0
    )

    hot_water_odn = forms.FloatField(
        widget=forms.TextInput(attrs=attrs),
        error_messages=error_messages,
        initial=0
    )

    cold_water = forms.FloatField(
        widget=forms.TextInput(attrs=attrs),
        error_messages=error_messages,
        initial=0
    )
    cold_water_odn = forms.FloatField(
        widget=forms.TextInput(attrs=attrs),
        error_messages=error_messages,
        initial=0
    )
    sewage = forms.FloatField(
        widget=forms.TextInput(attrs=attrs),
        error_messages=error_messages,
        initial=0
    )
    sewage_odn = forms.FloatField(
        widget=forms.TextInput(attrs=attrs),
        error_messages=error_messages,
        initial=0
    )
    solid_waste = forms.FloatField(
        widget=forms.TextInput(attrs=attrs),
        error_messages=error_messages,
        initial=0
    )
    electricity = forms.FloatField(
        widget=forms.TextInput(attrs=attrs),
        error_messages=error_messages,
        initial=0
    )
    lift = forms.FloatField(
        widget=forms.TextInput(attrs=attrs),
        error_messages=error_messages,
        initial=0
    )
    electricity_odn = forms.FloatField(
        widget=forms.TextInput(attrs=attrs),
        error_messages=error_messages,
        initial=0
    )
    capital_repair = forms.FloatField(
        widget=forms.TextInput(attrs=attrs),
        error_messages=error_messages,
        initial=0
    )

    multiplying_factor = forms.FloatField(
        widget=forms.TextInput(attrs=attrs),
        error_messages=error_messages,
        initial=0
    )

    class Meta:
        model = Tariff
        fields = "__all__"

tariff/views.py
import json

from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render
from django.urls import reverse_lazy
from django.views import View
from django.views.generic.list import ListView

from common.views import TitleMixin
from main.forms import SettingsForm
from main.models import Settings
from tariff.forms import TariffForm
from tariff.models import Tariff
from users.forms import UserLoginForm

from django.contrib.auth.decorators import login_required


class TariffBaseView(View):
    model = Tariff
    fields = '__all__'
    success_url = reverse_lazy('tariff:tariff_list')


def tariff_list(request):
    return render(request, 'tariff/tariff_list.html', {
        'tariff_list': Tariff.objects.all(),
    })


class TariffListView(TariffBaseView, TitleMixin, ListView):
    """View to list all tariffs.
    Use the 'tariff_list' variable in the template
    to access all Tariff objects"""
    template_name = 'tariff/index.html'
    title = 'Тарифы'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['settings_form'] = SettingsForm(instance=Settings.objects.get(id=1))
        context['login_form'] = UserLoginForm(data=self.request.POST)
        return context


@login_required
def add_tariff(request):
    if request.method == "POST":
        tariff_form = TariffForm(request.POST)
        if tariff_form.is_valid():
            tariff = tariff_form.save()
            return HttpResponse(
                status=204,
                headers={
                    'HX-Trigger': json.dumps({
                        "tariffListChanged": None,
                        "showMessage": f"Тариф {tariff.name} добавлен."
                    })
                })
    else:
        tariff_form = TariffForm()
    return render(request, 'tariff/edit.html', {
        'tariff_form': tariff_form,
        'title': 'СОЗДАНИЕ НОВОГО ТАРИФА',
    })


@login_required
def edit_tariff(request, pk):
    tariff = get_object_or_404(Tariff, pk=pk)
    if request.method == "POST":
        tariff_form = TariffForm(request.POST, instance=tariff)
        if tariff_form.is_valid():
            tariff_form.save()
            return HttpResponse(
                status=204,
                headers={
                    'HX-Trigger': json.dumps({
                        "tariffListChanged": None,
                        "showMessage": f"Тариф {tariff.name} изменен."
                    })
                }
            )
    else:
        tariff_form = TariffForm(instance=tariff)
    return render(request, 'tariff/edit.html', {
        'tariff_form': tariff_form,
        'tariff': tariff,
        'title': 'РЕДАКТИРОВАНИЕ ТАРИФА',
    })


@login_required
def remove_tariff(request, pk):
    tariff = get_object_or_404(Tariff, pk=pk)
    if request.method == "POST":
        tariff.delete()
        return HttpResponse(
            status=204,
            headers={
                'HX-Trigger': json.dumps({
                    "tariffListChanged": None,
                    "showMessage": f"Тариф {tariff.name} удален."
                })
            }
        )
    else:
        tariff_form = TariffForm(instance=tariff)
    return render(request, 'tariff/confirm_delete.html', {
        'tariff_form': tariff_form,
        'tariff': tariff,
        'tariff_name': tariff.name,
        'title': 'ПОДТВЕРЖДЕНИЕ ДЕЙСТВИЯ',
    })

tariff/templates/tariff/confirm_delete.html
{% load widget_tweaks %}
{% with WIDGET_ERROR_CLASS='is-invalid' %}
<form hx-post="{{ request.path }}" hx-headers='{"X-CSRFToken":"{{ csrf_token }}"}' class="modal-content">
  <div class="modal-content">
    <div class="modal-header text-center custom-modal-header">
      <h5 class="modal-title w-100" style="font-size: 14px; color: #FFFFFF; font-family: Segoe UI;">{{ title }}</h5>
    </div>
    <div class="modal-body">
      <div class="row mb-3">
        <div class="col" style="text-align: center;">
          <label class="form-label" style="margin-bottom: 0;">Are you sure you want to delete tariff </label>
          <label class="form-label" style="margin-bottom: 0; font-weight: bold;">"{{ tariff_name }}"</label>
          <label class="form-label" style="margin-bottom: 0;">?</label>
        </div>
      </div>
      <br>
      <div class="row mb-3">
        <div class="col text-center">
          <div class="d-grid gap-3 d-md-flex justify-content-md-center">
            <a class="btn-segoe" data-bs-dismiss="modal">Cancel</a>
            <a class="btn-segoe-primary" id="yesButton">Delete</a>
            <input type="submit" class="d-none" id="submitButtonYes">
          </div>
        </div>
      </div>
    </div>
  </div>
</form>
{% endwith %}

<script>
  document.getElementById("yesButton").addEventListener("click", function() {
    document.getElementById("submitButtonYes").click();
  });
</script>

tariff/templates/tariff/edit.html
{% load widget_tweaks %}
{% with WIDGET_ERROR_CLASS='is-invalid' %}
<form hx-post="{{ request.path }}" hx-headers='{"X-CSRFToken":"{{ csrf_token }}"}' class="modal-content">
    <div class="modal-content">
      <div class="modal-header text-center custom-modal-header">
        <h5 class="modal-title w-100" style="font-size: 14px; color: #FFFFFF; font-family: Segoe UI,serif; font-weight: 400">{{ title }}</h5>
      </div>
        <div class="modal-body">
          <div class="row mb-3">
            <div class="col">
              <label for="{{ tariff_form.name.id_for_label }}" class="form-label">Название:</label>
                {% render_field tariff_form.name class="form-control" %}
                <div class="invalid-feedback">{{ tariff_form.name.errors|first }}</div>
            </div>
            <div class="col">
              <label for="{{ tariff_form.hot_water_odn.id_for_label }}" class="form-label">Горячая вода (ОДН):</label>
              {% render_field tariff_form.hot_water_odn class="form-control" %}
              <div class="invalid-feedback">{{ tariff_form.hot_water_odn.errors|first }}</div>
            </div>
            <div class="col">
              <label for="{{ tariff_form.solid_waste.id_for_label }}" class="form-label">Обращение с ТКО:</label>
              {% render_field tariff_form.solid_waste class="form-control" %}
              <div class="invalid-feedback">{{ tariff_form.solid_waste.errors|first }}</div>
            </div>
          </div>
          <div class="row mb-3">
            <div class="col">
              <label for="{{ tariff_form.maintenance.id_for_label }}" class="form-label">Содержание жилья:</label>
              {% render_field tariff_form.maintenance class="form-control" %}
              <div class="invalid-feedback">{{ tariff_form.maintenance.errors|first }}</div>
            </div>
            <div class="col">
              <label for="{{ tariff_form.cold_water.id_for_label }}" class="form-label">Холодная вода:</label>
              {% render_field tariff_form.cold_water class="form-control" %}
              <div class="invalid-feedback">{{ tariff_form.cold_water.errors|first }}</div>
            </div>
            <div class="col">
              <label for="{{ tariff_form.electricity.id_for_label }}" class="form-label">Электроэнергия:</label>
              {% render_field tariff_form.electricity class="form-control" %}
              <div class="invalid-feedback">{{ tariff_form.electricity.errors|first }}</div>
            </div>
          </div>
          <div class="row mb-3">
            <div class="col">
              <label for="{{ tariff_form.heating.id_for_label }}" class="form-label">Отопление (Гкал):</label>
              {% render_field tariff_form.heating class="form-control" %}
              <div class="invalid-feedback">{{ tariff_form.heating.errors|first }}</div>
            </div>
            <div class="col">
              <label for="{{ tariff_form.cold_water_odn.id_for_label }}" class="form-label">Холодная вода (ОДН):</label>
              {% render_field tariff_form.cold_water_odn class="form-control" %}
              <div class="invalid-feedback">{{ tariff_form.cold_water_odn.errors|first }}</div>
            </div>
            <div class="col">
              <label for="{{ tariff_form.electricity_odn.id_for_label }}" class="form-label">Электроэнергия (ОДН):</label>
              {% render_field tariff_form.electricity_odn class="form-control" %}
              <div class="invalid-feedback">{{ tariff_form.electricity_odn.errors|first }}</div>
            </div>
          </div>
          <div class="row mb-3">
            <div class="col">
              <label for="{{ tariff_form.heating_rub.id_for_label }}" class="form-label">Отопление (Руб):</label>
              {% render_field tariff_form.heating_rub class="form-control" %}
              <div class="invalid-feedback">{{ tariff_form.heating_rub.errors|first }}</div>
            </div>
            <div class="col">
              <label for="{{ tariff_form.sewage.id_for_label }}" class="form-label">Водоотведение:</label>
              {% render_field tariff_form.sewage class="form-control" %}
              <div class="invalid-feedback">{{ tariff_form.sewage.errors|first }}</div>
            </div>
            <div class="col">
              <label for="{{ tariff_form.lift.id_for_label }}" class="form-label">Лифт:</label>
              {% render_field tariff_form.lift class="form-control" %}
              <div class="invalid-feedback">{{ tariff_form.lift.errors|first }}</div>
            </div>
          </div>
          <div class="row mb-3">
            <div class="col">
              <label for="{{ tariff_form.hot_water.id_for_label }}" class="form-label">Горячая вода:</label>
              {% render_field tariff_form.hot_water class="form-control" %}
              <div class="invalid-feedback">{{ tariff_form.hot_water.errors|first }}</div>
            </div>
            <div class="col">
              <label for="{{ tariff_form.sewage_odn.id_for_label }}" class="form-label">Канализация (ОДН):</label>
              {% render_field tariff_form.sewage_odn class="form-control" %}
              <div class="invalid-feedback">{{ tariff_form.sewage_odn.errors|first }}</div>
            </div>
            <div class="col">
              <label for="{{ tariff_form.capital_repair.id_for_label }}" class="form-label">Капитальный ремонт:</label>
              {% render_field tariff_form.capital_repair class="form-control" %}
              <div class="invalid-feedback">{{ tariff_form.capital_repair.errors|first }}</div>
            </div>
          </div>
          <div class="row mb-3">
            <div class="col">
              <label for="{{ tariff_form.multiplying_factor.id_for_label }}" class="form-label">Размер повышающего коэффициента:</label>
              {% render_field tariff_form.multiplying_factor class="form-control" %}
              <div class="invalid-feedback">{{ tariff_form.multiplying_factor.errors|first }}</div>
            </div>
            <div class="col">
            </div>
            <div class="col">
            </div>
          </div>
            <br>
          <div class="row mb-3">
            <div class="col text-center">
              <div class="d-grid gap-3 d-md-flex justify-content-md-center">
                <a class="btn-segoe" data-bs-dismiss="modal">Отменить</a>
                <a class="btn-segoe-primary" id="saveTariffButton">Сохранить</a>
                <input type="submit" class="d-none" id="submitButtonSaveTariff">
              </div>
            </div>
          </div>
        </div>
    </div>
</form>
{% endwith %}

<script>
  document.getElementById("saveTariffButton").addEventListener("click", function() {
    document.getElementById("submitButtonSaveTariff").click();
  });
</script>

tariff/templates/tariff/index.html
{% extends 'main/base.html' %}
{% load static %}

{% block css %}
    <link href="{% static 'css/apartment.css' %}" rel="stylesheet">
    <link href="{% static 'css/buttons.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}

{% for tariff in tariff_list  %}
    {% for colname in tariff.column_set.all  %}
        <p>{{ colname }}</p>
    {% endfor %}
{% endfor %}

<br>

<div class="container">
    <div class="row">
        <div class="col-sm-6 text-start">
            <h1 class="special2">Тарифы</h1>
        </div>
    </div>

<br>

<div class="row">
    <div class="col-sm-6">
         <a class="btn-segoe-main"
            hx-get="{% url 'tariff:add_tariff' %}"
            hx-target="#dialog">Добавить новый тариф</a>
    </div>
</div>

<br>

<table class="apartment-table">
        <colgroup>
            <col style="width: 5%;">
            <col style="width: 25%;">
            <col style="width: 7%;">
            <col style="width: 7%;">
            <col style="width: 7%;">
            <col style="width: 7%;">
            <col style="width: 20%;">
        </colgroup>
        <thead class="apartment-table">
            <tr>
                <th class="apartment-header">№</th>
                <th class="apartment-header">Наименование</th>
                <th class="apartment-header">Содержание жилья</th>
                <th class="apartment-header">Отопление (ГКал)</th>
                <th class="apartment-header">Отопление (рубли)</th>
                <th class="apartment-header">Горячая вода</th>
                <th class="apartment-header">Действие</th>
            </tr>
        </thead>
        <tbody hx-trigger="load, tariffListChanged from:body" hx-get="{% url 'tariff:tariff_list' %}" hx-target="this">
          <tr>
            <td class="dots-loader" role="status">
              <span class="visually-hidden">Loading...</span>
            </td>
          </tr>
        </tbody>
</table>

</div>

<!-- Placeholder for the modal edit tariff -->
    <div id="modal" class="modal fade">
      <div id="dialog" class="modal-dialog modal-dialog-centered modal-lg" hx-target="this"></div>
    </div>

<!-- Placeholder for the modal confirmation delete -->
    <div id="modal_conf" class="modal fade">
      <div id="confirmation" class="modal-dialog modal-dialog-centered" hx-target="this"></div>
    </div>

<!-- Empty toast to show the message -->
    <div class="toast-container position-fixed top-0 end-0 p-3">
      <div id="toast" class="toast align-items-center text-white bg-success border-0" role="alert" aria-live="assertive" aria-atomic="true">
        <div class="d-flex">
          <div id="toast-body" class="toast-body"></div>
          <button type="button" class="btn-close btn-close-white me-2 m-auto" data-bs-dismiss="toast" aria-label="Close"></button>
        </div>
      </div>
    </div>


<div class="back-to-top"></div>

<br>
<br>
<br>
<br>

<script>
    var backToTopButton = document.querySelector('.back-to-top');

    window.addEventListener('scroll', function() {
        if (window.pageYOffset > 100) {
            backToTopButton.style.display = 'block';
        } else {
            backToTopButton.style.display = 'none';
        }
    });

    backToTopButton.addEventListener('click', function() {
        window.scrollTo({
            top: 0,
            behavior: 'smooth'
        });
    });
</script>

{% endblock content %}

tariff/templates/tariff/tariff_list.html
{% for tariff in tariff_list %}
<tr>
  <td>
    <span class="apartment-nomer">{{ forloop.counter }}</span>
  </td>
  <td style="padding-left: 10px">{{ tariff.name }}</td>
  <td>{{ tariff.maintenance }}</td>
  <td>{{ tariff.heating }}</td>
  <td>{{ tariff.heating_rub }}</td>
  <td>{{ tariff.hot_water }}</td>
  <td>
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-5">
          <button class="edit-btn2" hx-get="{% url 'tariff:edit_tariff' pk=tariff.pk %}" hx-target="#dialog">Edit</button>
        </div>
        <div class="col-5">
          <button class="delete-btn2" hx-get="{% url 'tariff:tariff_delete' pk=tariff.pk %}" hx-target="#confirmation">Delete</button>
        </div>
      </div>
    </div>
  </td>
</tr>
{% endfor %}