main/urls.py
from django.urls import path

from main.views import (apartment_receipt, generate_excel,
                        generate_excel_apartment_total_file, generate_txt,
                        settings, update_fees)

app_name = 'main'

urlpatterns = [
    path('update_fees', update_fees, name='update_fees'),
    path('settings', settings, name='settings'),
    path('generate_excel', generate_excel, name='generate_excel'),
    path('generate_excel_apartment_total_file', generate_excel_apartment_total_file,
         name='generate_excel_apartment_total_file'),
    path('generate_txt', generate_txt, name='generate_txt'),
    path('apartment_receipt', apartment_receipt, name='apartment_receipt'),
]

rainbow/urls.py
from django.contrib import admin
from django.urls import include, path

from main import views
from main.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace='users')),
    path('', include('main.urls', namespace='main')),
    path('tariff/', include('tariff.urls', namespace='tariff')),
    path('repair/', include('repair.urls', namespace='repair')),
    path('', index, name='index'),
    path('update/<int:id>', views.update),

]

repair/urls.py
from django.urls import path

from repair.views import (RepairListView, edit_repair,
                          generate_excel_repair_total_file,
                          repair_generate_excel, repair_generate_txt,
                          repair_list, repairs_receipt)

app_name = 'repair'

urlpatterns = [
    path('', RepairListView.as_view(), name='repair_list_main'),
    path('list/', repair_list, name='repair_list'),
    path('<int:pk>/edit', edit_repair, name='edit_repair'),
    path('repair_generate_txt', repair_generate_txt, name='repair_generate_txt'),
    path('repair_generate_excel', repair_generate_excel, name='repair_generate_excel'),
    path(
        'generate_excel_repair_total_file', generate_excel_repair_total_file,
        name='generate_excel_repair_total_file'
        ),
    path('repair_receipt', repairs_receipt, name='repair_receipt'),
]

tariff/urls.py
from django.urls import path

from tariff.views import (TariffListView, add_tariff, edit_tariff,
                          remove_tariff, tariff_list)

app_name = 'tariff'

urlpatterns = [
    path('', TariffListView.as_view(), name='tariff_list_main'),
    path('list/', tariff_list, name='tariff_list'),
    path('add/', add_tariff, name='add_tariff'),
    path('<int:pk>/edit', edit_tariff, name='edit_tariff'),
    path('<int:pk>/delete/', remove_tariff, name='tariff_delete'),
]

users/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from users.views import login

app_name = 'users'

urlpatterns = [
    path('login/', login, name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

main/models.py
from django.db import models

from tariff.models import Tariff


class Apartment(models.Model):
    owner = models.CharField(max_length=200)
    serialNumber = models.IntegerField()

    def __str__(self):
        return str(self.serialNumber)


class ApartmentDetail(models.Model):
    registredQt = models.IntegerField()
    livedQt = models.IntegerField()
    totalArea = models.FloatField()
    personalAccount = models.IntegerField()
    serialNumber = models.ForeignKey(to=Apartment, on_delete=models.CASCADE)
    tariff = models.ForeignKey(to=Tariff, on_delete=models.DO_NOTHING, null=True, blank=True)
    account_number = models.CharField(max_length=200)


class ApartmentCounter(models.Model):
    hot_water_previous = models.IntegerField(default=0)
    hot_water_current = models.IntegerField(default=0)
    hot_water_value = models.IntegerField(default=0)
    cold_water_previous = models.IntegerField(default=0)
    cold_water_current = models.IntegerField(default=0)
    cold_water_value = models.IntegerField(default=0)
    electricity_previous = models.IntegerField(default=0)
    electricity_current = models.IntegerField(default=0)
    electricity_value = models.IntegerField(default=0)
    wastewater_value = models.IntegerField(default=0)
    serialNumber = models.ForeignKey(to=Apartment, on_delete=models.CASCADE)


class ApartmentCharge(models.Model):
    money_deposited = models.FloatField()
    fine = models.FloatField()
    recalculation_electricity = models.FloatField(null=True, blank=True)
    recalculation_heating_rub = models.FloatField(null=True, blank=True)
    recalculation_hot_water = models.FloatField(null=True, blank=True)
    recalculation_cold_water = models.FloatField(null=True, blank=True)
    recalculation_sewage = models.FloatField(null=True, blank=True)
    recalculation_solid_waste = models.FloatField(null=True, blank=True)
    recalculation_maintenance = models.FloatField(null=True, blank=True)
    balance_start = models.FloatField(null=True, blank=True)
    serialNumber = models.ForeignKey(to=Apartment, on_delete=models.CASCADE)


class ApartmentFee(models.Model):
    maintenance = models.FloatField(null=True, blank=True)
    electricity_odn = models.FloatField(null=True, blank=True)
    lift = models.FloatField(null=True, blank=True)
    maintenance_full = models.FloatField(null=True, blank=True)
    solid_waste = models.FloatField(null=True, blank=True)
    electricity = models.FloatField(null=True, blank=True)
    heating = models.FloatField(null=True, blank=True)
    heating_rub = models.FloatField(null=True, blank=True)
    hot_water = models.FloatField(null=True, blank=True)
    hot_water_odn = models.FloatField(null=True, blank=True)
    cold_water = models.FloatField(null=True, blank=True)
    cold_water_odn = models.FloatField(null=True, blank=True)
    sewage = models.FloatField(null=True, blank=True)
    sewage_odn = models.FloatField(null=True, blank=True)
    maintenance_total = models.FloatField(null=True, blank=True)
    accrued_expenses = models.FloatField(null=True, blank=True)
    recalculation = models.FloatField(null=True, blank=True)
    balance_start = models.FloatField(null=True, blank=True)
    balance_end = models.FloatField(null=True, blank=True)
    paid = models.FloatField(null=True, blank=True)
    fine = models.FloatField(null=True, blank=True)
    total = models.FloatField(null=True, blank=True)
    serialNumber = models.ForeignKey(to=Apartment, on_delete=models.CASCADE)


class Settings(models.Model):
    month_name = models.CharField(max_length=200)
    month_to_pay = models.CharField(max_length=200)
    month_to_date = models.CharField(max_length=200)
    bill = models.CharField(max_length=200)
    pay_up_to = models.CharField(max_length=200)

    class Meta:
        verbose_name = 'setting'
        verbose_name_plural = 'settings'

tariff/models.py
from django.db import models


class Tariff(models.Model):
    name = models.CharField(max_length=200)
    maintenance = models.FloatField(null=True, blank=True)
    heating = models.FloatField(null=True, blank=True)
    heating_rub = models.FloatField(null=True, blank=True)
    hot_water = models.FloatField(null=True, blank=True)
    hot_water_odn = models.FloatField(null=True, blank=True)
    cold_water = models.FloatField(null=True, blank=True)
    cold_water_odn = models.FloatField(null=True, blank=True)
    sewage = models.FloatField(null=True, blank=True)
    sewage_odn = models.FloatField(null=True, blank=True)
    solid_waste = models.FloatField(null=True, blank=True)
    electricity = models.FloatField(null=True, blank=True)
    lift = models.FloatField(null=True, blank=True)
    electricity_odn = models.FloatField(null=True, blank=True)
    capital_repair = models.FloatField(null=True, blank=True, default=0)
    multiplying_factor = models.FloatField(null=True, blank=True, default=1)

    class Meta:
        verbose_name = 'tariff'
        verbose_name_plural = 'tariffs'

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.name = self.name.capitalize()
        super(Tariff, self).save(*args, **kwargs)

main/views.py
from django.shortcuts import redirect, render

from main.calculation import calculate_fees
from main.excel import (export_client_bank, export_excel_apartment_total_file,
                        generate_excel_file)
from main.forms import (ApartmentChargeForm, ApartmentCounterForm,
                        ApartmentDetailForm, Settings, SettingsForm)
from main.models import (Apartment, ApartmentCharge, ApartmentCounter,
                         ApartmentDetail, ApartmentFee)
from main.pdf_generator import generate_pdf
from users.forms import UserLoginForm

from django.contrib import messages
from django.contrib.auth.decorators import login_required


@login_required
def settings(request):
    form = SettingsForm(instance=Settings.objects.get(id=1))
    if request.method == 'POST':
        form = SettingsForm(request.POST, instance=Settings.objects.get(id=1))
        if form.is_valid():
            form.save()
            return redirect('index')
        else:
            print(form.errors)
    context = {
        'settings_form': form,
    }
    return render(request, 'main/settings_form.html', context)


def index(request):
    filter_criteria = request.GET.get('filter')
    if filter_criteria == 'balance_end_gt_6000':
        apartments = Apartment.objects.filter(apartmentfee__balance_end__gt=6000)
    else:
        apartments = Apartment.objects.all()
    context = {
        'title': 'ТСЖ Радуга',
        'apartments': apartments,
        'apartment_details': ApartmentDetail.objects.all(),
        'apartment_fees': ApartmentFee.objects.all(),
        'apartment_charges': ApartmentCharge.objects.all(),
        'settings_form': SettingsForm(instance=Settings.objects.get(id=1)),
        'login_form': UserLoginForm(data=request.POST)
    }
    return render(request, 'main/index.html', context)


@login_required
def update(request, id):
    form = ApartmentDetailForm(instance=ApartmentDetail.objects.get(serialNumber=id))
    counterform = ApartmentCounterForm(instance=ApartmentCounter.objects.get(serialNumber=id))
    chargeform = ApartmentChargeForm(instance=ApartmentCharge.objects.get(serialNumber=id))
    prev_url = f"/update/{int(id) - 1}"
    next_url = f"/update/{int(id) + 1}"

    shortOwnerName = Apartment.objects.get(serialNumber=id).owner.split()
    shortOwnerName = f"{shortOwnerName[0]} {shortOwnerName[1][0]}.{shortOwnerName[2][0]}."

    if request.method == 'POST':
        if 'details' in request.POST:
            form = ApartmentDetailForm(
                request.POST, instance=ApartmentDetail.objects.get(serialNumber=id)
                )
            if form.is_valid():
                form.save()
                messages.success(request, 'Изменения сохранены!')
                return redirect(request.path_info)
            else:
                pass
                # messages.error(request, 'Ошибка - ' + str(form.errors))
        elif 'counters' in request.POST:
            counterform = ApartmentCounterForm(
                request.POST, instance=ApartmentCounter.objects.get(
                    serialNumber=id
                    )
                )
            if counterform.is_valid():
                counterform.save()
                messages.success(request, 'Изменения сохранены!')
                return redirect(request.path_info)
            else:
                pass
                # messages.error(request, 'Ошибка - ' + str(counterform.errors))
        elif 'charge' in request.POST:
            chargeform = ApartmentChargeForm(
                request.POST, instance=ApartmentCharge.objects.get(serialNumber=id)
                )
            if chargeform.is_valid():
                chargeform.save()
                messages.success(request, 'Изменения сохранены!')
                return redirect(request.path_info)
            else:
                pass
                # messages.error(request, 'Ошибка - ' + str(chargeform.errors))
    context = {
        'form': form,
        'counterform': counterform,
        'chargeform': chargeform,
        'prev_url': prev_url,
        'next_url': next_url,
        'page_num': id,
        'shortOwnerName': shortOwnerName,
        'settings_form': SettingsForm(instance=Settings.objects.get(id=1)),
        'login_form': UserLoginForm(data=request.POST)
    }
    return render(request, 'main/edit.html', context)


def update_fees(request):
    calculate_fees()
    return redirect('index')


def generate_excel(request):
    filter_criteria = request.GET.get('filter')
    if filter_criteria == 'balance_end_gt_6000':
        apartments = Apartment.objects.filter(apartmentfee__balance_end__gt=6000)
    else:
        apartments = Apartment.objects.all()
    response = generate_excel_file(apartments)
    return response


def generate_excel_apartment_total_file(request):
    response = export_excel_apartment_total_file()
    return response


def generate_txt(request):
    response = export_client_bank()
    return response


def apartment_receipt(request):
    pdf = generate_pdf()
    return pdf

tariff/views.py
import json

from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render
from django.urls import reverse_lazy
from django.views import View
from django.views.generic.list import ListView

from common.views import TitleMixin
from main.forms import SettingsForm
from main.models import Settings
from tariff.forms import TariffForm
from tariff.models import Tariff
from users.forms import UserLoginForm

from django.contrib.auth.decorators import login_required


class TariffBaseView(View):
    model = Tariff
    fields = '__all__'
    success_url = reverse_lazy('tariff:tariff_list')


def tariff_list(request):
    return render(request, 'tariff/tariff_list.html', {
        'tariff_list': Tariff.objects.all(),
    })


class TariffListView(TariffBaseView, TitleMixin, ListView):
    """View to list all tariffs.
    Use the 'tariff_list' variable in the template
    to access all Tariff objects"""
    template_name = 'tariff/index.html'
    title = 'Тарифы'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['settings_form'] = SettingsForm(instance=Settings.objects.get(id=1))
        context['login_form'] = UserLoginForm(data=self.request.POST)
        return context


@login_required
def add_tariff(request):
    if request.method == "POST":
        tariff_form = TariffForm(request.POST)
        if tariff_form.is_valid():
            tariff = tariff_form.save()
            return HttpResponse(
                status=204,
                headers={
                    'HX-Trigger': json.dumps({
                        "tariffListChanged": None,
                        "showMessage": f"Тариф {tariff.name} добавлен."
                    })
                })
    else:
        tariff_form = TariffForm()
    return render(request, 'tariff/edit.html', {
        'tariff_form': tariff_form,
        'title': 'СОЗДАНИЕ НОВОГО ТАРИФА',
    })


@login_required
def edit_tariff(request, pk):
    tariff = get_object_or_404(Tariff, pk=pk)
    if request.method == "POST":
        tariff_form = TariffForm(request.POST, instance=tariff)
        if tariff_form.is_valid():
            tariff_form.save()
            return HttpResponse(
                status=204,
                headers={
                    'HX-Trigger': json.dumps({
                        "tariffListChanged": None,
                        "showMessage": f"Тариф {tariff.name} изменен."
                    })
                }
            )
    else:
        tariff_form = TariffForm(instance=tariff)
    return render(request, 'tariff/edit.html', {
        'tariff_form': tariff_form,
        'tariff': tariff,
        'title': 'РЕДАКТИРОВАНИЕ ТАРИФА',
    })


@login_required
def remove_tariff(request, pk):
    tariff = get_object_or_404(Tariff, pk=pk)
    if request.method == "POST":
        tariff.delete()
        return HttpResponse(
            status=204,
            headers={
                'HX-Trigger': json.dumps({
                    "tariffListChanged": None,
                    "showMessage": f"Тариф {tariff.name} удален."
                })
            }
        )
    else:
        tariff_form = TariffForm(instance=tariff)
    return render(request, 'tariff/confirm_delete.html', {
        'tariff_form': tariff_form,
        'tariff': tariff,
        'tariff_name': tariff.name,
        'title': 'ПОДТВЕРЖДЕНИЕ ДЕЙСТВИЯ',
    })

main/templates/main/apartment_base.html
{% extends 'main/base.html' %}
{% load static %}

{% block css %}
{% endblock %}

{% block apartment_header %}

<div class="container">

    <br>

    <div class="row">
        <div class="col-sm-6 text-start">
            <h1 class="special2">Apartments</h1>
        </div>
    </div>

    <br>

    <div class="row">
        <div class="col-sm-6">
             <a class="btn-segoe-main" onclick="window.location.href='{% url 'main:update_fees' %}'">Recalculating</a>
             <a class="btn-segoe-main" onclick="window.location.href='{% url 'main:generate_excel' %}?filter={{ request.GET.filter }}'">Excel</a>
             <a class="btn-segoe-main" onclick="window.location.href='{% url 'main:apartment_receipt' %}'">Receipts</a>
             <a class="btn-segoe-main" onclick="window.location.href='{% url 'main:generate_txt' %}'">For bank app</a>
             <a class="btn-segoe-main" onclick="window.location.href='{% url 'main:generate_excel_apartment_total_file' %}'">Summary</a>
        </div>
        <div class="col-sm-6 text-end">
          <form method="get" action="{% url 'index' %}">
            <label for="filter">Choose a filter:</label>
            <select name="filter" id="filter">
              <option value="">All records</option>
              <option value="balance_end_gt_6000">Debtors  (balance end &gt; 6000)</option>
            </select>
          </form>
        </div>
    </div>
</div>

<br>

{% endblock %}

main/templates/main/base.html
{% load static %}

<!DOCTYPE html>
<html>
  <head>
    <title>{{ title }}</title>
    <link rel="icon" href="{% static 'favicon.ico' %}">
    <link href="{% static 'css/bootstrap_5.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/base.css' %}" rel="stylesheet">
    <link href="{% static 'css/apartmentEdit.css' %}" rel="stylesheet">
    <link href="{% static 'css/apartment_base.css' %}" rel="stylesheet">
    <link href="{% static 'css/popup.css' %}" rel="stylesheet">
    <link href="{% static 'css/apartment.css' %}" rel="stylesheet">
    {% block css %} {% endblock %}
  </head>

  <body>
    <div style="position: relative;">
      <img src="{% static 'img/header.jpg' %}" style="width:100%; height:auto;" alt="header">
      <div class="position-absolute" style="height:30px; background: rgba(89, 0, 168, 0.4); bottom: 10px; left: 0; right: 0;">
        <div class="container">
          <div class="row">
            <div class="col-sm-6 text-start">
              {% if title == 'Rainbow' %}
              {% else %}
              <a href="{% url 'index' %}" class="my-link">Apartments</a>
              <span class="ms-3"></span>
              {% endif %}
              {% if title == 'Tariffs' %}
              {% else %}
              <a href="{% url 'tariff:tariff_list_main' %}" class="my-link">Tariffs</a>
              <span class="ms-3"></span>
              {% endif %}
              {% if title == 'Complete overhaul' %}
              {% else %}
              <a href="{% url 'repair:repair_list_main' %}" class="my-link">Complete overhaul</a>
              <span class="ms-3"></span>
              {% endif %}
            </div>
            <div class="col-sm-6 text-end">
              <a href="" class="my-link" data-bs-toggle="modal" data-bs-target="#SettingsModal">Settings</a>
              <span class="ms-3"></span>
              {% if user.is_authenticated %}
              <a href="{% url 'users:logout' %}" class="my-link">Log out</a>
              {% else %}
              <a href="" class="my-link" data-bs-toggle="modal" data-bs-target="#LoginModal">Sign in</a>
              {% endif %}
            </div>
          </div>
        </div>
      </div>
      <div class="position-absolute top-50 start-50 translate-middle">
        <h1 class="text-center special">Homeowners association «Rainbow»</h1>
      </div>
    </div>

    <!-- Add the content blocks -->
    {% block apartment_header %} {% endblock %}
    {% block repair_header %} {% endblock %}
    {% block content %} {% endblock %}

    {% include 'main/settings_form.html' %}
    {% include 'login.html' %}

    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'js/htmx.min.js' %}"></script>
    <script src="{% static "js/dialog.js" %}"></script>
    <script src="{% static "js/confirmation.js" %}"></script>
    <script src="{% static "js/toast.js" %}"></script>
</body>

<footer>
</footer>


</html>

main/templates/main/index.html
{% extends 'main/apartment_base.html' %}
{% load static %}
{% load humanize %}

{% block css %}
    <link href="{% static 'css/apartment_base.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}

    <div class="container">
    <table class="apartment-table">
        <colgroup>
            <col style="width: 3%;">
            <col style="width: 22%;">
            <col style="width: 7%;">
            <col style="width: 7%;">
            <col style="width: 7%;">
            <col style="width: 7%;">
            <col style="width: 7%;">
            <col style="width: 7%;">
            <col style="width: 7%;">
            <col style="width: 7%;">
            <col style="width: 7%;">
            <col style="width: 7%;">
        </colgroup>
        <thead class="apartment-table">
            <tr>
                <th class="apartment-header">№</th>
                <th class="apartment-header">Landlord</th>
                <th class="apartment-header">Number of residents</th>
                <th class="apartment-header">Apartment size</th>
                <th class="apartment-header">Maintenance fee</th>
                <th class="apartment-header">Accrued</th>
                <th class="apartment-header">Recalculating</th>
                <th class="apartment-header">Balance (start)</th>
                <th class="apartment-header">Balance (End)</th>
                <th class="apartment-header">Paid</th>
                <th class="apartment-header">Fine</th>
                <th class="apartment-header">Total amount due</th>
            </tr>
        </thead>
        <tbody>
            {% for apartment in apartments %}
            <tr onclick="location.href='/update/{{ apartment.serialNumber }}';" style="cursor:pointer;">
                <td>
                    <span class="apartment-nomer">{{ apartment.serialNumber }}</span>
                </td>
                <td>
                    <span class="apartment-owner">{{ apartment.owner }}</span>
                </td>
                {% for detail in apartment.apartmentdetail_set.all %}
                <td>{{ detail.livedQt }}</td>
                <td>{{ detail.totalArea }}</td>
                {% endfor %}
                {% for apartment_fee in apartment.apartmentfee_set.all %}
                <td>{{ apartment_fee.maintenance|intcomma }}</td>
                <td>{{ apartment_fee.accrued_expenses|intcomma }}</td>
                <td>{{ apartment_fee.recalculation|intcomma }}</td>
                <td>{{ apartment_fee.balance_start|intcomma }}</td>
                <td>{{ apartment_fee.balance_end|intcomma }}</td>
                <td>{{ apartment_fee.paid|intcomma }}</td>
                <td>{{ apartment_fee.fine|intcomma }}</td>
                <td>{{ apartment_fee.total|intcomma }}</td>
                {% endfor %}
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

<div class="back-to-top"></div>

<br>
<br>
<br>
<br>

<script>
    var backToTopButton = document.querySelector('.back-to-top');

    window.addEventListener('scroll', function() {
        if (window.pageYOffset > 100) {
            backToTopButton.style.display = 'block';
        } else {
            backToTopButton.style.display = 'none';
        }
    });

    backToTopButton.addEventListener('click', function() {
        window.scrollTo({
            top: 0,
            behavior: 'smooth'
        });
    });
</script>


<script>
  // get the filter select element
  const filterSelect = document.getElementById('filter');

  // get the current filter value from the query string
  const urlParams = new URLSearchParams(window.location.search);
  const currentFilter = urlParams.get('filter');

  // set the selected option in the filter select element based on the current filter value
  if (currentFilter === 'balance_end_gt_6000') {
    filterSelect.value = 'balance_end_gt_6000';
  }

  // add event listener to the filter select element
  filterSelect.addEventListener('change', function() {
    // get the selected option value
    const selectedValue = this.value;

    // construct the new URL based on the selected option value
    let newUrl = window.location.origin + window.location.pathname;
    if (selectedValue) {
      newUrl += '?filter=' + selectedValue;
    }

    // redirect to the new URL
    window.location.href = newUrl;
  });
</script>


{% endblock %}

main/templates/main/messages.html
{% for message in messages %}
  <div class="alert {{ message.tags }} alert-dismissible fade show" role="alert" style="width: 400px">

    {{ message }}
  </div>
{% endfor %}

main/templates/main/settings_form.html
<div class="modal fade" id="SettingsModal" tabindex="-1" aria-labelledby="settingsModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header text-center custom-modal-header">
        <h5 class="modal-title w-100" style="font-size: 14px; color: #FFFFFF; font-family: Segoe UI,serif; font-weight: 400">SETTINGS</h5>
      </div>
      <form action="{% url 'main:settings' %}" method="post">
        {% csrf_token %}
        <div class="modal-body">
          <div class="row mb-3">
            <div class="col">
              <label for="{{ settings_form.month_name.id_for_label }}" class="form-label">Month:</label>
              {{ settings_form.month_name }}
            </div>
          </div>
          <div class="row mb-3">
            <div class="col">
              <label for="{{ settings_form.month_to_pay.id_for_label }}" class="form-label">To be paid for (month):</label>
              {{ settings_form.month_to_pay }}
            </div>
            <div class="col">
              <label for="{{ settings_form.bill.id_for_label }}" class="form-label">Notification Bill:</label>
              {{ settings_form.bill }}
            </div>
          </div>
          <div class="row mb-3">
            <div class="col">
              <label for="{{ settings_form.month_to_date.id_for_label }}" class="form-label">To be paid for (date):</label>
              {{ settings_form.month_to_date }}
            </div>
            <div class="col">
              <label for="{{ settings_form.pay_up_to.id_for_label }}" class="form-label">Pay before:</label>
              {{ settings_form.pay_up_to }}
            </div>
          </div>
          <br>
          <div class="row mb-3">
            <div class="col text-center">
              <div class="d-grid gap-3 d-md-flex justify-content-md-center">
                <a class="btn-segoe" data-bs-dismiss="modal">Cancel</a>
                <a class="btn-segoe-primary" id="saveSettingsButton">Save</a>
                <input type="submit" class="d-none" id="submitButtonSaveSettings">
              </div>
            </div>
          </div>
        </div>
      </form>
    </div>
  </div>
</div>

<script>
  document.getElementById("saveSettingsButton").addEventListener("click", function() {
    document.getElementById("submitButtonSaveSettings").click();
  });
</script>

main/templates/main/tariff_list.html
{% extends 'main/base.html' %}

{% block content %}

{% for tariff in tariff_list  %}
    {% for colname in tariff.column_set.all  %}
        <p>{{ colname }}</p>
    {% endfor %}
{% endfor %}


<div class="container d-flex mt-5" style="width: 70%;">
    <div class="col">
        <h1 class="text-center">Тарифы/Расценки</h1>
        <table class="table table-striped mt-5">
            <thead>
                <tr>
                    {% comment %} <th>#</th> {% endcomment %}
                    <th class="text-center" scope="col">Наименование</th>
                    <th>Содержания жилья</th>
                    <th>Подогрев воды ГКал</th>
                    <th>Подогрев воды рубли</th>
                    <th>Горячая вода</th>
                    <th></th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
            
                {% for tariff in tariff_list  %}
                <tr>
                    {% comment %} <th scope="row">{{forloop.counter}}</th> {% endcomment %}
                    <td class="ml-5">{{tariff.name}}</td>
                    <td class="ml-5">{{tariff.maintenance}}</td>
                    <td class="ml-5">{{tariff.heating}}</td>
                    <td class="ml-5">{{tariff.heating_rub}}</td>
                    <td class="ml-5">{{tariff.hot_water}}</td>
                    <td><a href="{% url 'main:tariff_update' tariff.id %} ">Редактировать</a></td>
                    <td><a href="{% url 'main:tariff_delete' tariff.id %}">Удалить</a></td>
                </tr>
            {% endfor %}
        
            </tbody>
        </table>    
        <div class="d-flex justify-content-center">
            <a href="{% url 'main:tariff_create' %}" class="d-block btn btn-primary btn-lg my-5">Добавить новый тариф</a>
        </div>
    </div>
        
</div>

{% endblock content %}